/* You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t. */

var findTheDifference = function(s, t) {
  let sumS = 0;
  let sumT = 0;

  for (let i = 0; i < t.length; i++) {
      if (i !== t.length - 1) sumS += s.charCodeAt(i);
      sumT += t.charCodeAt(i);
  }

  let difference = sumT - sumS;
  return String.fromCharCode(difference);
};